[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
extra_scripts =
    pre:autorev.py
lib_deps =
    adafruit/Adafruit EPD
    h2zero/NimBLE-Arduino

[env:panel]
board = adafruit_feather_esp32s3
build_flags =
    '-D EPD_EN=(6)'
    '-D EPD_BUSY=(9)'
    '-D EPD_RESET=(10)'
    '-D SRAM_CS=(11)'
    '-D EPD_DC=(12)'
    '-D EPD_CS=(13)'
