[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit EPD

[env:feather]
board = adafruit_feather_esp32s3
# TODO: wire up EPD_RESET and EPD_BUSY to some pins,
#       they are pads on the bottom of the e-ink friend
# NOTE: the feather has 2MB of PSRAM onboard, no need to
#       use the 32k of SRAM on the e-ink friend
build_flags =
    '-D EPD_DC=(10)'
    '-D EPD_RESET=(-1)'
    '-D EPD_CS=(9)'
    '-D SRAM_CS=(-1)'
    '-D EPD_BUSY=(-1)'
