[env]
platform = espressif32@^6.10.0
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200

[env:s3]
board = esp32-s3-devkitm-1
build_flags =
	'-D I2C_SDA0_PIN=((gpio_num_t)1)'
	'-D I2C_SCL0_PIN=((gpio_num_t)1)'

[env:qt]
board = adafruit_qtpy_esp32s3_nopsram
build_flags =
	'-D I2C_SDA0_PIN=((gpio_num_t)1)'
	'-D I2C_SCL0_PIN=((gpio_num_t)1)'
